name: build

permissions:
  contents: write

on:
  push:
    paths-ignore:
      - "**.md"
    branches: ["main"]
  pull_request:
    paths-ignore:
      - "**.md"
    branches: ["main"]

jobs:
  native:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Cache Deps
        uses: actions/cache@v4.0.0
        with:
          path: ~/.m2/repository
          key: linux-${{ hashFiles('deps.edn') }}
          restore-keys: linux-

      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: "21.0.2"
          distribution: "graalvm"
          native-image-musl: true
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Clojure CLI
        uses: DeLaGuardo/setup-clojure@12.3
        with:
          cli: 1.11.1.1435

      - name: Download Deps
        run: clojure -A:build -P

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install build-essential zlib1g-dev
    
      - name: Shai Version
        id: shai-version
        run: |
          SHAI_VERSION=$(clojure -T:build print-version)
          echo "Shai version: ${SHAI_VERSION}"
          echo "version=${SHAI_VERSION}" >> $GITHUB_OUTPUT

      - name: Build Uberjar
        run: clojure -T:build uber

      - name: Build Native Image Executable
        run: bash native.sh

      - name: Upload Executable
        uses: actions/upload-artifact@v4.3.0
        with:
          name: shai-${{ steps.shai-version.outputs.version }}-linux-static-amd64
          path: target/shai
          retention-days: 1
      
      - name: Rename Executable
        run: mv target/shai target/shai-${{ steps.shai-version.outputs.version }}-linux-static-amd64

      - name: Create SHA1
        run: sha1sum target/shai-${{ steps.shai-version.outputs.version }}-linux-static-amd64 > target/shai-${{ steps.shai-version.outputs.version }}-linux-static-amd64.sha1
      
      - name: Release
        uses: softprops/action-gh-release@v1
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
          files: |
            target/shai-${{ steps.shai-version.outputs.version }}-linux-static-amd64
            target/shai-${{ steps.shai-version.outputs.version }}-linux-static-amd64.sha1
          tag_name: v${{ steps.shai-version.outputs.version }}
          body: |
            Shai v${{ steps.shai-version.outputs.version }} release
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}